spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  public-key: ${RSA_PUBLIC_KEY:file:/app/certs/public.pem}
  private-key: ${RSA_PRIVATE_KEY:file:/app/certs/private.pem}

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  environment: ${SPRING_PROFILES_ACTIVE:development}