name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Устанавливаем Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Кэшируем зависимости Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 4. Права на gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Генерируем RSA ключи перед сборкой
      - name: Generate RSA keys
        run: |
          mkdir -p src/main/resources/certs
          openssl genrsa -out src/main/resources/certs/private.pem 2048
          openssl rsa -in src/main/resources/certs/private.pem \
            -pubout -out src/main/resources/certs/public.pem

      # Сборка фронтенда
      - name: Install and build frontend
        run: |
          npm i @hexlet/java-task-manager-frontend
          npx build-frontend

      # 5. Собираем проект и запускаем тесты
      - name: Build with Gradle
        run: ./gradlew build

      # 6. Запускаем анализ SonarQube
      - name: SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
